application: compareroute-v1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /img
  static_dir: static/img

- url: /img/(.*\.png)
  mime_type: text/javascript
  static_files: static/img/\1
  upload: static/img/(.*\.png)

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /less
  static_dir: static/less

- url: /fonts/(.*\.wotf)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.wotf)
  mime_type: application/x-font-otf

- url: /fonts
#  mime_type: application/x-font-otf
  static_dir: static/fonts

- url: /sorting
  script: handlers.sorting_prep.app

- url: /sorting_comp
  script: handlers.sorting_prep.app

- url: /api/.*
  script: rest_main.app

- url: /api/truck_capacity/v1
  script: rest_main.app

- url: /api/truck_capacity/v1
  script: rest_main.app

- url: /api/multi_companies/v1
  script: rest_main.app

- url: /sorting-result-proposed
  script: handlers.sorting_prep.app

- url: /sorting-result-current
  script: handlers.sorting_prep.app

- url: /sorting-summary
  script: handlers.sorting_prep.app

- url: /sorting-latlng
  script: handlers.sorting_prep.app

- url: /json/capacity
  script: handlers.capacity.app

- url: /json/capacity_speed
  script: handlers.capacity_speed.app

- url: /json
  script: handlers.Json.app

- url: /email_info
  script: handlers.email_info.app

- url: /.*
  script: main.app

- url: /.*
  script: route.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: endpoints
  version: 1.0
